### ISSUE TITLE
Doesn't affect barrier blocks

### ISSUE THREAD

**Issue by QueenUlyana** [Roundaround/mc-fabric-true-sight#1] opened 2023-05-23 16:36 UTC
I don't see invisible barriers. The mod doesn't work.
![2023-05-23_19 34 58](https://github.com/Roundaround/mc-fabric-true-sight/assets/83131824/fe7a71ac-0a62-43a0-a743-97687ae6d285)

**Comment by Roundaround** [comment] 2023-05-24 02:29
If you're talking about barrier blocks, that is intentional. They are blocks, and this mod reveals invisible entities.

If you want to see barrier blocks, just search Google for a resource pack that gives them a texture.

**Comment by Roundaround** [comment] 2023-05-24 23:29
Closing since this is intended behavior.

**Closed as not planned by Roundaround** 2023-05-24 23:29 UTC
